<a href="https://colab.research.google.com/github/vkquests/Data_Manipulation_Project/blob/main/data_manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Manipulation Project
##Introduction
 Raw data is rarely in the ideal format for analysis or utilization. This is where data manipulation comes into play â€“ a crucial process that involves transforming, cleaning, and structuring data to extract valuable insights and drive meaningful conclusions.

 In this data manipulation project, we delve into turning raw data into actionable knowledge. My aim is to showcase the significance of data preprocessing, cleansing, and transformation.

## Project Goals
We have data from a survey, that has gathered responses from individuals to various questions, aiming to discern key trends and patterns.
Specifically, we are interested in two aspects:
* Number of unique respondents for each question and
* Frequency of identical answers received for specific questions.

This analysis will provide us with valuable insights into participant engagement and common trends within the survey data.

## Data Preprocessing in Excel

Before commencing data analysis in Python, critical data preprocessing was carried out in Microsoft Excel. The process primarily involved transforming the raw data, initially stored in a sheet named **Raw_data** into a format conducive to further analysis. The cleaned and formatted data was then saved in an **Edited_data** sheet, which served as the foundation for subsequent data manipulations in Python.


### Header and Subheader Combination
The raw data initially had headers and subheaders in separate rows. To address this, we merged the header and subheader into a single row.

* Step 1: Copy the header row.
* Step 2: Use the "Paste Special" function and select "Transpose" to convert the rows into columns(unpivot). This step was repeated for both the header and subheader rows.

### Concatenation of Columns
After transposing both the header and subheader rows into columns, we concatenated these columns. This process involved combining the header and subheader columns into one unified column.

* Step 3: Concatenate the columns containing the header and subheader data into a single column. This created a clear and comprehensible representation of the column names.

### Transposing Columns Back to Rows
With the data now organized as a single column containing the combined headers and subheaders, we needed to transpose it back to rows. This was achieved using the "Paste Special" function.

* Step 4: Copy the concatenated column.
* Step 5: Once again, use the "Paste Special" function, but this time, select "Transpose" to convert the columns back into rows(pivot). The result was a clean and well-structured dataset ready for Python data manipulation.

These preprocessing steps in Excel were pivotal in simplifying the data structure and preparing it for effective analysis in Python. By combining and transposing rows and columns strategically, we ensured that the data was in a format conducive to our data manipulation efforts, enabling us to derive meaningful insights from the survey data.

This Excel-based data preprocessing served as a foundational step in our data manipulation project, setting the stage for subsequent analysis and exploration using Python and Pandas.

## Code

Importing Libraries   
 We start by importing the necessary libraries. In this project, we rely on Pandas for data manipulation.

In [1]:
import pandas as pd

Reading Raw Data  
We read the 'Edited_data' sheet from an Excel file ('Survey_Data.xlsx') and create a copy of the dataframe to work on.

In [2]:
df_read = pd.read_excel('/content/Survey_Data.xlsx', sheet_name='Edited_data')
df_read

,Respondent ID,Start Date,End Date,Email Address,First Name,Last Name,Custom Data 1,Identify which division you work in.-Response,Identify which division you work in.-Other (please specify),Which of the following best describes your position level?-Response,...,Question 29-Response 8,Question 29-Response 9,Question 29-Response 10,Question 29-Response 11,Question 29-Response 12,Question 29-Response 13,Question 29-Response 14,Question 30-Response 1,Question 30-Response 2,Question 30-Response 3
0,5379192392,2021-01-22 12:01:17,2021-01-22 12:40:34,NaN,NaN,NaN,NaN,Infrastructure,NaN,Staff,...,NaN,Answer 8,Answer 8,Answer 4,NaN,NaN,Answer 5,NaN,NaN,NaN
1,2658722536,2021-01-22 06:56:37,2021-01-22 07:34:10,NaN,NaN,NaN,NaN,Finance,NaN,Staff,...,NaN,Answer 5,NaN,NaN,Answer 2,NaN,Answer 5,NaN,NaN,Answer 1
2,4044163394,2021-01-22 06:35:18,2021-01-22 06:47:32,NaN,NaN,NaN,NaN,Infrastructure,NaN,Department Lead,...,NaN,NaN,Answer 4,Answer 4,Answer 6,NaN,Answer 6,NaN,Answer 1,NaN
3,5535865599,2021-01-21 21:29:32,2021-01-21 21:40:24,NaN,NaN,NaN,NaN,Infrastructure,NaN,Manager,...,Answer 2,Answer 5,Answer 7,NaN,Answer 6,NaN,Answer 7,Answer 7,Answer 1,Answer 6
4,3356802928,2021-01-21 17:26:39,2021-01-21 17:44:40,NaN,NaN,NaN,NaN,Port Operations,NaN,Manager,...,NaN,Answer 5,Answer 4,Answer 4,Answer 7,Answer 7,NaN,Answer 7,NaN,Answer 8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,7940065082,2021-01-11 06:19:18,2021-01-11 06:32:59,NaN,NaN,NaN,NaN,Infrastructure,NaN,Department Lead,...,Answer 1,Answer 1,Answer 3,Answer 6,Answer 6,Answer 8,NaN,NaN,NaN,Answer 8
194,5157705612,2021-01-11 06:19:14,2021-01-11 06:33:29,NaN,NaN,NaN,NaN,Finance,NaN,Staff,...,Answer 5,NaN,Answer 5,NaN,NaN,Answer 2,NaN,NaN,NaN,Answer 6
195,9920755555,2021-01-11 06:18:48,2021-01-11 06:27:27,NaN,NaN,NaN,NaN,Port Operations,NaN,Staff,...,NaN,Answer 7,NaN,NaN,NaN,NaN,NaN,NaN,Answer 3,NaN
196,6638341389,2021-01-11 06:19:01,2021-01-11 06:33:06,NaN,NaN,NaN,NaN,Infrastructure,NaN,Manager,...,Answer 2,NaN,Answer 3,Answer 5,NaN,Answer 8,Answer 3,Answer 3,NaN,NaN
197,8114622230,2021-01-11 06:18:50,2021-01-11 06:26:46,NaN,NaN,NaN,NaN,Information Technology,NaN,Staff,...,Answer 3,NaN,Answer 7,NaN,NaN,NaN,NaN,Answer 3,NaN,NaN

Take a copy of the dataframe and work on the copy

In [3]:
df = df_read.copy()

### Data Transformation   
Dropping Unwanted Columns   
We identify and drop unnecessary columns from the dataset.

In [4]:
df.columns

Index(['Respondent ID', 'Start Date', 'End Date', 'Email Address',
       'First Name', 'Last Name', 'Custom Data 1',
       'Identify which division you work in.-Response',
       'Identify which division you work in.-Other (please specify)',
       'Which of the following best describes your position level?-Response',
       'Which generation are you apart of?-Response',
       'Please select the gender in which you identify.-Response',
       'Which duration range best aligns with your tenure at your company?-Response',
       'Which of the following best describes your employment type?-Response',
       'Question 1-Response', 'Question 2-Response',
       'Question 3-Open-Ended Response', 'Question 4-Response',
       'Question 4-Other (please specify)', 'Question 5-Response 1',
       'Question 5-Response 2', 'Question 5-Response 3',
       'Question 5-Response 4', 'Question 5-Response 5',
       'Question 5-Response 6', 'Question 6-Response 1',
       'Question 6-Response 2', 'Question 6-Response 3',
       'Question 6-Response 4', 'Question 6-Response 5',
       'Question 6-Response 6', 'Question 7-Response 1',
       'Question 7-Unscheduled', 'Question 8-Response 1',
       'Question 8-Response 2', 'Question 8-Response 3',
       'Question 8-Response 4', 'Question 9-Response 1',
       'Question 9-Response 2', 'Question 9-Response 3',
       'Question 9-Response 4', 'Question 10-Response 1',
       'Question 10-Response 2', 'Question 10-Response 3',
       'Question 10-Response 4', 'Question 10-Response 5',
       'Question 11-Reponse 1', 'Question 11-Response 2',
       'Question 12-Response', 'Question 13-Response', 'Question 14-Response',
       'Question 15-Response', 'Question 16-Response', 'Question 17-Response',
       'Question 18-Response', 'Question 19-Response',
       'Question 19-Other (please specify)', 'Question 20-Response',
       'Question 21-Response', 'Question 22-Reponse 1',
       'Question 22-Reponse 2', 'Question 23-Response',
       'Question 24-Response 1', 'Question 24-Response 2',
       'Question 24-Response 3', 'Question 24-Response 4',
       'Question 24-Response 5', 'Question 25-Response 1',
       'Question 25-Response 2', 'Question 25-Response 3',
       'Question 25-Response 4', 'Question 25-Response 5',
       'Question 25-Response 6', 'Question 25-Response 7',
       'Question 25-Response 8', 'Question 25-Response 9',
       'Question 26-Response 1', 'Question 26-Response 2',
       'Question 26-Response 3', 'Question 26-Response 4',
       'Question 27-Response 1', 'Question 27-Response 2',
       'Question 28-Response', 'Question 29-Response 1',
       'Question 29-Response 2', 'Question 29-Response 3',
       'Question 29-Response 4', 'Question 29-Response 5',
       'Question 29-Response 6', 'Question 29-Response 7',
       'Question 29-Response 8', 'Question 29-Response 9',
       'Question 29-Response 10', 'Question 29-Response 11',
       'Question 29-Response 12', 'Question 29-Response 13',
       'Question 29-Response 14', 'Question 30-Response 1',
       'Question 30-Response 2', 'Question 30-Response 3'],
      dtype='object')

In [5]:
columns_to_drop = ['Start Date', 'End Date', 'Email Address','First Name', 'Last Name', 'Custom Data 1']

In [6]:
df = df.drop(columns=columns_to_drop)
df

,Respondent ID,Identify which division you work in.-Response,Identify which division you work in.-Other (please specify),Which of the following best describes your position level?-Response,Which generation are you apart of?-Response,Please select the gender in which you identify.-Response,Which duration range best aligns with your tenure at your company?-Response,Which of the following best describes your employment type?-Response,Question 1-Response,Question 2-Response,...,Question 29-Response 8,Question 29-Response 9,Question 29-Response 10,Question 29-Response 11,Question 29-Response 12,Question 29-Response 13,Question 29-Response 14,Question 30-Response 1,Question 30-Response 2,Question 30-Response 3
0,5379192392,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,0-2 years,Full time Employee,NaN,Answer 6,...,NaN,Answer 8,Answer 8,Answer 4,NaN,NaN,Answer 5,NaN,NaN,NaN
1,2658722536,Finance,NaN,Staff,NaN,NaN,10+ years,Full time Employee,Answer 4,Answer 2,...,NaN,Answer 5,NaN,NaN,Answer 2,NaN,Answer 5,NaN,NaN,Answer 1
2,4044163394,Infrastructure,NaN,Department Lead,Generation X (born between 1965-1980),Male,3-5 years,Full time Employee,Answer 5,Answer 7,...,NaN,NaN,Answer 4,Answer 4,Answer 6,NaN,Answer 6,NaN,Answer 1,NaN
3,5535865599,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Non-Binary,5-10 years,Full time Employee,Answer 1,Answer 1,...,Answer 2,Answer 5,Answer 7,NaN,Answer 6,NaN,Answer 7,Answer 7,Answer 1,Answer 6
4,3356802928,Port Operations,NaN,Manager,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,NaN,Answer 3,...,NaN,Answer 5,Answer 4,Answer 4,Answer 7,Answer 7,NaN,Answer 7,NaN,Answer 8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,7940065082,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Answer 3,NaN,...,Answer 1,Answer 1,Answer 3,Answer 6,Answer 6,Answer 8,NaN,NaN,NaN,Answer 8
194,5157705612,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,NaN,NaN,...,Answer 5,NaN,Answer 5,NaN,NaN,Answer 2,NaN,NaN,NaN,Answer 6
195,9920755555,Port Operations,NaN,Staff,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,NaN,Answer 7,...,NaN,Answer 7,NaN,NaN,NaN,NaN,NaN,NaN,Answer 3,NaN
196,6638341389,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,NaN,NaN,...,Answer 2,NaN,Answer 3,Answer 5,NaN,Answer 8,Answer 3,Answer 3,NaN,NaN
197,8114622230,Information Technology,NaN,Staff,Prefer not to answer,Male,5-10 years,Full time Employee,NaN,Answer 1,...,Answer 3,NaN,Answer 7,NaN,NaN,NaN,NaN,Answer 3,NaN,NaN

Data Unpivoting   
We use the pd.melt function to unpivot the data, transforming it from a wide format to a long format. This facilitates further analysis.

In [7]:
id_var = df.columns[0:8]
id_var

Index(['Respondent ID', 'Identify which division you work in.-Response',
       'Identify which division you work in.-Other (please specify)',
       'Which of the following best describes your position level?-Response',
       'Which generation are you apart of?-Response',
       'Please select the gender in which you identify.-Response',
       'Which duration range best aligns with your tenure at your company?-Response',
       'Which of the following best describes your employment type?-Response'],
      dtype='object')

In [8]:
#Column(s) to unpivot
value_var = df.columns[8:]
value_var

Index(['Question 1-Response', 'Question 2-Response',
       'Question 3-Open-Ended Response', 'Question 4-Response',
       'Question 4-Other (please specify)', 'Question 5-Response 1',
       'Question 5-Response 2', 'Question 5-Response 3',
       'Question 5-Response 4', 'Question 5-Response 5',
       'Question 5-Response 6', 'Question 6-Response 1',
       'Question 6-Response 2', 'Question 6-Response 3',
       'Question 6-Response 4', 'Question 6-Response 5',
       'Question 6-Response 6', 'Question 7-Response 1',
       'Question 7-Unscheduled', 'Question 8-Response 1',
       'Question 8-Response 2', 'Question 8-Response 3',
       'Question 8-Response 4', 'Question 9-Response 1',
       'Question 9-Response 2', 'Question 9-Response 3',
       'Question 9-Response 4', 'Question 10-Response 1',
       'Question 10-Response 2', 'Question 10-Response 3',
       'Question 10-Response 4', 'Question 10-Response 5',
       'Question 11-Reponse 1', 'Question 11-Response 2',
       'Question 12-Response', 'Question 13-Response', 'Question 14-Response',
       'Question 15-Response', 'Question 16-Response', 'Question 17-Response',
       'Question 18-Response', 'Question 19-Response',
       'Question 19-Other (please specify)', 'Question 20-Response',
       'Question 21-Response', 'Question 22-Reponse 1',
       'Question 22-Reponse 2', 'Question 23-Response',
       'Question 24-Response 1', 'Question 24-Response 2',
       'Question 24-Response 3', 'Question 24-Response 4',
       'Question 24-Response 5', 'Question 25-Response 1',
       'Question 25-Response 2', 'Question 25-Response 3',
       'Question 25-Response 4', 'Question 25-Response 5',
       'Question 25-Response 6', 'Question 25-Response 7',
       'Question 25-Response 8', 'Question 25-Response 9',
       'Question 26-Response 1', 'Question 26-Response 2',
       'Question 26-Response 3', 'Question 26-Response 4',
       'Question 27-Response 1', 'Question 27-Response 2',
       'Question 28-Response', 'Question 29-Response 1',
       'Question 29-Response 2', 'Question 29-Response 3',
       'Question 29-Response 4', 'Question 29-Response 5',
       'Question 29-Response 6', 'Question 29-Response 7',
       'Question 29-Response 8', 'Question 29-Response 9',
       'Question 29-Response 10', 'Question 29-Response 11',
       'Question 29-Response 12', 'Question 29-Response 13',
       'Question 29-Response 14', 'Question 30-Response 1',
       'Question 30-Response 2', 'Question 30-Response 3'],
      dtype='object')

In [9]:
df_melted = pd.melt(df,id_vars=id_var, value_vars=value_var, var_name='Question_plus_Subquestion', value_name='Answer' )
df_melted

,Respondent ID,Identify which division you work in.-Response,Identify which division you work in.-Other (please specify),Which of the following best describes your position level?-Response,Which generation are you apart of?-Response,Please select the gender in which you identify.-Response,Which duration range best aligns with your tenure at your company?-Response,Which of the following best describes your employment type?-Response,Question_plus_Subquestion,Answer
0,5379192392,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,0-2 years,Full time Employee,Question 1-Response,NaN
1,2658722536,Finance,NaN,Staff,NaN,NaN,10+ years,Full time Employee,Question 1-Response,Answer 4
2,4044163394,Infrastructure,NaN,Department Lead,Generation X (born between 1965-1980),Male,3-5 years,Full time Employee,Question 1-Response,Answer 5
3,5535865599,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Non-Binary,5-10 years,Full time Employee,Question 1-Response,Answer 1
4,3356802928,Port Operations,NaN,Manager,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1-Response,NaN
...,...,...,...,...,...,...,...,...,...,...
17023,7940065082,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 30-Response 3,Answer 8
17024,5157705612,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Question 30-Response 3,Answer 6
17025,9920755555,Port Operations,NaN,Staff,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30-Response 3,NaN
17026,6638341389,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30-Response 3,NaN
17027,8114622230,Information Technology,NaN,Staff,Prefer not to answer,Male,5-10 years,Full time Employee,Question 30-Response 3,NaN

Reading Questions Data  
We read the 'Question' sheet from the same Excel file, which contains information about the survey questions.

In [10]:
#importing Question sheet
questions = pd.read_excel('/content/Survey_Data.xlsx', sheet_name='Question')
questions

,Raw Question,Raw Subquestion,Question,Subquestion,Question + Subquestion(Formula),Question + Subquestion
0,Respondent ID,NaN,Respondent ID,NaN,Respondent ID,Respondent ID
1,Start Date,NaN,Start Date,NaN,Start Date,Start Date
2,End Date,NaN,End Date,NaN,End Date,End Date
3,Email Address,NaN,Email Address,NaN,Email Address,Email Address
4,First Name,NaN,First Name,NaN,First Name,First Name
...,...,...,...,...,...,...
95,NaN,Response 13,Question 29,Response 13,Question 29-Response 13,Question 29-Response 13
96,NaN,Response 14,Question 29,Response 14,Question 29-Response 14,Question 29-Response 14
97,Question 30,Response 1,Question 30,Response 1,Question 30-Response 1,Question 30-Response 1
98,NaN,Response 2,Question 30,Response 2,Question 30-Response 2,Question 30-Response 2
99,NaN,Response 3,Question 30,Response 3,Question 30-Response 3,Question 30-Response 3

Dropping Unwanted Columns in Questions Data   
We identify and drop unnecessary columns from the questions dataset to retain only relevant information.  
We are interested in 'Question' column and 'Question + Subquestion' is required to join to with df_melted

In [11]:
questions = questions.drop(columns={'Raw Question','Raw Subquestion','Subquestion',	'Question + Subquestion(Formula)'})
questions

         Question   Question + Subquestion
0   Respondent ID            Respondent ID
1      Start Date               Start Date
2        End Date                 End Date
3   Email Address            Email Address
4      First Name               First Name
..            ...                      ...
95    Question 29  Question 29-Response 13
96    Question 29  Question 29-Response 14
97    Question 30   Question 30-Response 1
98    Question 30   Question 30-Response 2
99    Question 30   Question 30-Response 3

[100 rows x 2 columns]

Merging DataFrames  
We merge the unpivoted survey data (df_melted) with the questions data (questions) based on the 'Question_plus_Subquestion' column.

In [12]:
df_merged = pd.merge(left=df_melted ,right=questions ,how='left' ,left_on='Question_plus_Subquestion' , right_on='Question + Subquestion' )
df_merged

,Respondent ID,Identify which division you work in.-Response,Identify which division you work in.-Other (please specify),Which of the following best describes your position level?-Response,Which generation are you apart of?-Response,Please select the gender in which you identify.-Response,Which duration range best aligns with your tenure at your company?-Response,Which of the following best describes your employment type?-Response,Question_plus_Subquestion,Answer,Question,Question + Subquestion
0,5379192392,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,0-2 years,Full time Employee,Question 1-Response,NaN,Question 1,Question 1-Response
1,2658722536,Finance,NaN,Staff,NaN,NaN,10+ years,Full time Employee,Question 1-Response,Answer 4,Question 1,Question 1-Response
2,4044163394,Infrastructure,NaN,Department Lead,Generation X (born between 1965-1980),Male,3-5 years,Full time Employee,Question 1-Response,Answer 5,Question 1,Question 1-Response
3,5535865599,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Non-Binary,5-10 years,Full time Employee,Question 1-Response,Answer 1,Question 1,Question 1-Response
4,3356802928,Port Operations,NaN,Manager,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1-Response,NaN,Question 1,Question 1-Response
...,...,...,...,...,...,...,...,...,...,...,...,...
17023,7940065082,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 30-Response 3,Answer 8,Question 30,Question 30-Response 3
17024,5157705612,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Question 30-Response 3,Answer 6,Question 30,Question 30-Response 3
17025,9920755555,Port Operations,NaN,Staff,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30-Response 3,NaN,Question 30,Question 30-Response 3
17026,6638341389,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30-Response 3,NaN,Question 30,Question 30-Response 3
17027,8114622230,Information Technology,NaN,Staff,Prefer not to answer,Male,5-10 years,Full time Employee,Question 30-Response 3,NaN,Question 30,Question 30-Response 3

Dropping Redundant Column   
We drop the 'Question + Subquestion' column, which contains the same data as 'Question_plus_Subquestion.'

In [13]:
df_merged=df_merged.drop(columns=['Question + Subquestion'])
df_merged

,Respondent ID,Identify which division you work in.-Response,Identify which division you work in.-Other (please specify),Which of the following best describes your position level?-Response,Which generation are you apart of?-Response,Please select the gender in which you identify.-Response,Which duration range best aligns with your tenure at your company?-Response,Which of the following best describes your employment type?-Response,Question_plus_Subquestion,Answer,Question
0,5379192392,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,0-2 years,Full time Employee,Question 1-Response,NaN,Question 1
1,2658722536,Finance,NaN,Staff,NaN,NaN,10+ years,Full time Employee,Question 1-Response,Answer 4,Question 1
2,4044163394,Infrastructure,NaN,Department Lead,Generation X (born between 1965-1980),Male,3-5 years,Full time Employee,Question 1-Response,Answer 5,Question 1
3,5535865599,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Non-Binary,5-10 years,Full time Employee,Question 1-Response,Answer 1,Question 1
4,3356802928,Port Operations,NaN,Manager,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1-Response,NaN,Question 1
...,...,...,...,...,...,...,...,...,...,...,...
17023,7940065082,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 30-Response 3,Answer 8,Question 30
17024,5157705612,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Question 30-Response 3,Answer 6,Question 30
17025,9920755555,Port Operations,NaN,Staff,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30-Response 3,NaN,Question 30
17026,6638341389,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30-Response 3,NaN,Question 30
17027,8114622230,Information Technology,NaN,Staff,Prefer not to answer,Male,5-10 years,Full time Employee,Question 30-Response 3,NaN,Question 30

### Data Analysis
Counting Unique Respondents   
We identify and count the number of unique respondents for each question, considering only questions that were answered.

In [14]:
# we are condidering only questions that were answered
respondants = df_merged[df_merged['Answer'].notna()]
respondants = respondants.groupby('Question')['Respondent ID'].nunique().reset_index()
respondants

#reset_index() to make respondants series into a df to rename the column

       Question  Respondent ID
0    Question 1            119
1   Question 10            198
2   Question 11            164
3   Question 12            114
4   Question 13            108
5   Question 14            105
6   Question 15            114
7   Question 16            117
8   Question 17            135
9   Question 18            109
10  Question 19            157
11   Question 2            118
12  Question 20            105
13  Question 21            127
14  Question 22            160
15  Question 23            120
16  Question 24            195
17  Question 25            198
18  Question 26            193
19  Question 27            153
20  Question 28            119
21  Question 29            198
22   Question 3            117
23  Question 30            182
24   Question 4            161
25   Question 5            194
26   Question 6            196
27   Question 7            162
28   Question 8            190
29   Question 9            188

Rename column

In [15]:
# renaming Respondent ID columns of respondants df before joining
respondants = respondants.rename(columns={'Respondent ID':'Respondents_Count'})
respondants

       Question  Respondents_Count
0    Question 1                119
1   Question 10                198
2   Question 11                164
3   Question 12                114
4   Question 13                108
5   Question 14                105
6   Question 15                114
7   Question 16                117
8   Question 17                135
9   Question 18                109
10  Question 19                157
11   Question 2                118
12  Question 20                105
13  Question 21                127
14  Question 22                160
15  Question 23                120
16  Question 24                195
17  Question 25                198
18  Question 26                193
19  Question 27                153
20  Question 28                119
21  Question 29                198
22   Question 3                117
23  Question 30                182
24   Question 4                161
25   Question 5                194
26   Question 6                196
27   Question 7                162
28   Question 8                190
29   Question 9                188

Joining DataFrames  
We join the 'respondants' dataframe with the main dataframe (df_merged) to add the 'Respondents_Count' column.

In [16]:
df_merged2 = pd.merge(left=df_merged, right=respondants, how='left', left_on='Question', right_on='Question')
print(len(df_merged))
print(len(df_merged2))
df_merged2

17028
17028

,Respondent ID,Identify which division you work in.-Response,Identify which division you work in.-Other (please specify),Which of the following best describes your position level?-Response,Which generation are you apart of?-Response,Please select the gender in which you identify.-Response,Which duration range best aligns with your tenure at your company?-Response,Which of the following best describes your employment type?-Response,Question_plus_Subquestion,Answer,Question,Respondents_Count
0,5379192392,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,0-2 years,Full time Employee,Question 1-Response,NaN,Question 1,119
1,2658722536,Finance,NaN,Staff,NaN,NaN,10+ years,Full time Employee,Question 1-Response,Answer 4,Question 1,119
2,4044163394,Infrastructure,NaN,Department Lead,Generation X (born between 1965-1980),Male,3-5 years,Full time Employee,Question 1-Response,Answer 5,Question 1,119
3,5535865599,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Non-Binary,5-10 years,Full time Employee,Question 1-Response,Answer 1,Question 1,119
4,3356802928,Port Operations,NaN,Manager,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1-Response,NaN,Question 1,119
...,...,...,...,...,...,...,...,...,...,...,...,...
17023,7940065082,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 30-Response 3,Answer 8,Question 30,182
17024,5157705612,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Question 30-Response 3,Answer 6,Question 30,182
17025,9920755555,Port Operations,NaN,Staff,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30-Response 3,NaN,Question 30,182
17026,6638341389,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30-Response 3,NaN,Question 30,182
17027,8114622230,Information Technology,NaN,Staff,Prefer not to answer,Male,5-10 years,Full time Employee,Question 30-Response 3,NaN,Question 30,182

Counting Identical Answers  
We calculate the number of identical answers received for specific questions, including 'not answered' responses.

In [17]:
#Finding out repondants with same answer to a given question incl 'not answered' for same question
same_answer = df_merged
same_answer = same_answer.groupby(['Question_plus_Subquestion','Answer'])['Respondent ID'].nunique().reset_index()
same_answer = same_answer.rename(columns={'Respondent ID':'Same_Answer_Count'})
same_answer

    Question_plus_Subquestion    Answer  Same_Answer_Count
0         Question 1-Response  Answer 1                 14
1         Question 1-Response  Answer 2                 10
2         Question 1-Response  Answer 3                 13
3         Question 1-Response  Answer 4                 17
4         Question 1-Response  Answer 5                 22
..                        ...       ...                ...
683     Question 9-Response 4  Answer 4                 16
684     Question 9-Response 4  Answer 5                 13
685     Question 9-Response 4  Answer 6                 14
686     Question 9-Response 4  Answer 7                 12
687     Question 9-Response 4  Answer 8                 19

[688 rows x 3 columns]

Joining DataFrames  
We join the 'same_answer' dataframe with the main dataframe (df_merged2) to add the 'Same_Answer_Count' column.

In [18]:
df_merged3 = pd.merge(left=df_merged2, right=same_answer, how='left', left_on=['Question_plus_Subquestion', 'Answer'], right_on=['Question_plus_Subquestion', 'Answer'])
print(len(df_merged2))
print(len(df_merged3))
df_merged3

17028
17028

,Respondent ID,Identify which division you work in.-Response,Identify which division you work in.-Other (please specify),Which of the following best describes your position level?-Response,Which generation are you apart of?-Response,Please select the gender in which you identify.-Response,Which duration range best aligns with your tenure at your company?-Response,Which of the following best describes your employment type?-Response,Question_plus_Subquestion,Answer,Question,Respondents_Count,Same_Answer_Count
0,5379192392,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,0-2 years,Full time Employee,Question 1-Response,NaN,Question 1,119,NaN
1,2658722536,Finance,NaN,Staff,NaN,NaN,10+ years,Full time Employee,Question 1-Response,Answer 4,Question 1,119,17.0
2,4044163394,Infrastructure,NaN,Department Lead,Generation X (born between 1965-1980),Male,3-5 years,Full time Employee,Question 1-Response,Answer 5,Question 1,119,22.0
3,5535865599,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Non-Binary,5-10 years,Full time Employee,Question 1-Response,Answer 1,Question 1,119,14.0
4,3356802928,Port Operations,NaN,Manager,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1-Response,NaN,Question 1,119,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
17023,7940065082,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 30-Response 3,Answer 8,Question 30,182,14.0
17024,5157705612,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Question 30-Response 3,Answer 6,Question 30,182,20.0
17025,9920755555,Port Operations,NaN,Staff,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30-Response 3,NaN,Question 30,182,NaN
17026,6638341389,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30-Response 3,NaN,Question 30,182,NaN
17027,8114622230,Information Technology,NaN,Staff,Prefer not to answer,Male,5-10 years,Full time Employee,Question 30-Response 3,NaN,Question 30,182,NaN

Handling Missing Values   
We fill missing values in the 'Same_Answer_Count' column with 0.

In [19]:
# fill NAN as 0 for 'Same_Answer_Count'
#df_merged3['Same_Answer_Count'].fillna(0, inplace=True) #using inplace
df_merged3['Same_Answer_Count'] = df_merged3['Same_Answer_Count'].fillna(0)
df_merged3

,Respondent ID,Identify which division you work in.-Response,Identify which division you work in.-Other (please specify),Which of the following best describes your position level?-Response,Which generation are you apart of?-Response,Please select the gender in which you identify.-Response,Which duration range best aligns with your tenure at your company?-Response,Which of the following best describes your employment type?-Response,Question_plus_Subquestion,Answer,Question,Respondents_Count,Same_Answer_Count
0,5379192392,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,0-2 years,Full time Employee,Question 1-Response,NaN,Question 1,119,0.0
1,2658722536,Finance,NaN,Staff,NaN,NaN,10+ years,Full time Employee,Question 1-Response,Answer 4,Question 1,119,17.0
2,4044163394,Infrastructure,NaN,Department Lead,Generation X (born between 1965-1980),Male,3-5 years,Full time Employee,Question 1-Response,Answer 5,Question 1,119,22.0
3,5535865599,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Non-Binary,5-10 years,Full time Employee,Question 1-Response,Answer 1,Question 1,119,14.0
4,3356802928,Port Operations,NaN,Manager,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1-Response,NaN,Question 1,119,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
17023,7940065082,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 30-Response 3,Answer 8,Question 30,182,14.0
17024,5157705612,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Question 30-Response 3,Answer 6,Question 30,182,20.0
17025,9920755555,Port Operations,NaN,Staff,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30-Response 3,NaN,Question 30,182,0.0
17026,6638341389,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30-Response 3,NaN,Question 30,182,0.0
17027,8114622230,Information Technology,NaN,Staff,Prefer not to answer,Male,5-10 years,Full time Employee,Question 30-Response 3,NaN,Question 30,182,0.0

In [20]:
output = df_merged3.copy()

In [21]:
#renaming some of the columns
output.columns

Index(['Respondent ID', 'Identify which division you work in.-Response',
       'Identify which division you work in.-Other (please specify)',
       'Which of the following best describes your position level?-Response',
       'Which generation are you apart of?-Response',
       'Please select the gender in which you identify.-Response',
       'Which duration range best aligns with your tenure at your company?-Response',
       'Which of the following best describes your employment type?-Response',
       'Question_plus_Subquestion', 'Answer', 'Question', 'Respondents_Count',
       'Same_Answer_Count'],
      dtype='object')

Rename columns

In [22]:
#as dict items
output = output.rename(columns={'Identify which division you work in.-Response' : 'Division_Primary',
       'Identify which division you work in.-Other (please specify)' : 'Division_Secondary',
       'Which of the following best describes your position level?-Response' :'Position',
       'Which generation are you apart of?-Response': 'Generation',
       'Please select the gender in which you identify.-Response' : 'Gender',
       'Which duration range best aligns with your tenure at your company?-Response' : 'Tenure',
       'Which of the following best describes your employment type?-Response' : 'Employment_Type'})
output

,Respondent ID,Division_Primary,Division_Secondary,Position,Generation,Gender,Tenure,Employment_Type,Question_plus_Subquestion,Answer,Question,Respondents_Count,Same_Answer_Count
0,5379192392,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,0-2 years,Full time Employee,Question 1-Response,NaN,Question 1,119,0.0
1,2658722536,Finance,NaN,Staff,NaN,NaN,10+ years,Full time Employee,Question 1-Response,Answer 4,Question 1,119,17.0
2,4044163394,Infrastructure,NaN,Department Lead,Generation X (born between 1965-1980),Male,3-5 years,Full time Employee,Question 1-Response,Answer 5,Question 1,119,22.0
3,5535865599,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Non-Binary,5-10 years,Full time Employee,Question 1-Response,Answer 1,Question 1,119,14.0
4,3356802928,Port Operations,NaN,Manager,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1-Response,NaN,Question 1,119,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
17023,7940065082,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 30-Response 3,Answer 8,Question 30,182,14.0
17024,5157705612,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Question 30-Response 3,Answer 6,Question 30,182,20.0
17025,9920755555,Port Operations,NaN,Staff,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30-Response 3,NaN,Question 30,182,0.0
17026,6638341389,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30-Response 3,NaN,Question 30,182,0.0
17027,8114622230,Information Technology,NaN,Staff,Prefer not to answer,Male,5-10 years,Full time Employee,Question 30-Response 3,NaN,Question 30,182,0.0

Output  
The cleaned and processed data is saved as 'Final_Data.csv.'

In [23]:
output.to_csv('Final_Data.csv', index=False)

Checking data in the csv

In [24]:
new = pd.read_csv('/content/Final_Data.csv')
new

,Respondent ID,Division_Primary,Division_Secondary,Position,Generation,Gender,Tenure,Employment_Type,Question_plus_Subquestion,Answer,Question,Respondents_Count,Same_Answer_Count
0,5379192392,Infrastructure,NaN,Staff,Generation X (born between 1965-1980),Male,0-2 years,Full time Employee,Question 1-Response,NaN,Question 1,119,0.0
1,2658722536,Finance,NaN,Staff,NaN,NaN,10+ years,Full time Employee,Question 1-Response,Answer 4,Question 1,119,17.0
2,4044163394,Infrastructure,NaN,Department Lead,Generation X (born between 1965-1980),Male,3-5 years,Full time Employee,Question 1-Response,Answer 5,Question 1,119,22.0
3,5535865599,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Non-Binary,5-10 years,Full time Employee,Question 1-Response,Answer 1,Question 1,119,14.0
4,3356802928,Port Operations,NaN,Manager,Generation X (born between 1965-1980),Female,10+ years,Full time Employee,Question 1-Response,NaN,Question 1,119,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
17023,7940065082,Infrastructure,NaN,Department Lead,Baby Boomer (born between 1946-1964),Male,10+ years,Full time Employee,Question 30-Response 3,Answer 8,Question 30,182,14.0
17024,5157705612,Finance,NaN,Staff,Millennial (born between 1981-2000),Female,5-10 years,Full time Employee,Question 30-Response 3,Answer 6,Question 30,182,20.0
17025,9920755555,Port Operations,NaN,Staff,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30-Response 3,NaN,Question 30,182,0.0
17026,6638341389,Infrastructure,NaN,Manager,Millennial (born between 1981-2000),Female,3-5 years,Full time Employee,Question 30-Response 3,NaN,Question 30,182,0.0
17027,8114622230,Information Technology,NaN,Staff,Prefer not to answer,Male,5-10 years,Full time Employee,Question 30-Response 3,NaN,Question 30,182,0.0

## Conclusion
Data manipulation is a critical step in the data analysis process. This project demonstrates how to preprocess, clean, and structure raw survey data to extract valuable insights and address specific business questions.

## Conclusion
Data manipulation is an indispensable step in the data analysis journey. This project showcases the importance of this process, where we have taken raw survey data and meticulously transformed it into a structured, analyzable form. Through this endeavor, we have not only gained valuable insights but also laid the groundwork for addressing specific business questions and making informed decisions.

Key Takeaways from this Project:

**Data Preprocessing:** We started by recognizing that raw data is rarely in the ideal format for analysis. Thus, we engaged in data preprocessing, including data cleaning and transformation, to ensure the data was suitable for analysis.

**Structuring Data:** The process of unpivoting data from a wide format to a long format was instrumental in organizing the information for analysis. This step facilitated a more comprehensive exploration of the dataset.

**Merging and Joining Data:** We effectively merged different datasets, combining survey responses with question details. This integration provided context to the responses and enhanced the depth of our analysis.

**Unique Respondent Count:** By calculating the number of unique respondents for each question, we gained insights into participant engagement. This metric helps us understand the reach and relevance of individual questions within the survey.

**Identical Answer Frequency:** Determining the frequency of identical answers for specific questions shed light on common trends in responses. This information is crucial for identifying patterns and making data-driven decisions.

In conclusion, data manipulation is the foundation upon which data analysis rests. It allows us to extract actionable knowledge from raw data, making it a vital step in any data-centric project. This project not only demonstrates the techniques involved but also emphasizes the significance of data preprocessing, cleansing, and transformation in uncovering valuable insights and addressing specific business inquiries.

By following the processes outlined in this project, we can apply similar techniques to different datasets, unlocking the potential for data-driven decision-making and achieving meaningful conclusions.

As we embark on the data analysis journey, remember that data manipulation is both an art and a science, enabling us to reveal hidden stories within the data and derive actionable insights for informed decision-making.